version: "3.3"

services:
  telegram:
    build:
      context: .
      dockerfile: Dockerfile-dev
    container_name: telegram
    networks:
      - water-system
    volumes:
      - .:/app
    environment:
      TELEGRAM_TOKEN: ${TELEGRAM_TOKEN:-:token}
      TELEGRAM_WS_URL: ${TELEGRAM_WS_URL:-http://water_system:8080}
      TELEGRAM_WS_TOKEN: ${TELEGRAM_WS_TOKEN:-WT7*P6Yn^2-Y*V*C-h&K6*b!@=HCzhd+}
networks:
  water-system:
    external: true