- hosts: raspberry_telegram
  tasks:
    - name: Build binary
      local_action:
        module: make
        chdir: ..
        target: build
    - name: Stopping supervisor
      shell: supervisorctl stop "{{ service_name}}"
      become: yes
    - name: Copy old binary file
      shell: cp {{ binary_path }} {{ binary_path }}_old
    - name: Upload binary file
      copy:
        src: assets/telegram
        dest: "{{ binary_path }}"
        mode: 0750
        force: yes
    - name: Upload config file
      template:
        src: config/config.yml.j2
        dest: "{{ home }}/config_telegram.yml"
        mode: 0750
        force: yes
    - name: Upload supervisor conf file
      template:
        src: config/telegram.conf
        dest: /etc/supervisor/conf.d/telegram.conf
        mode: 0750
        force: yes
      become: yes
    - name: Reload config supervisor
      shell: supervisorctl reload
      become: yes
    - name: Start supervisor
      shell: supervisorctl start "{{ service_name}}"
      become: yes