// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package domain

import (
	"sync"
)

var (
	lockTemperatureRepositoryMockGet sync.RWMutex
)

// Ensure, that TemperatureRepositoryMock does implement TemperatureRepository.
// If this is not the case, regenerate this file with moq.
var _ TemperatureRepository = &TemperatureRepositoryMock{}

// TemperatureRepositoryMock is a mock implementation of TemperatureRepository.
//
//     func TestSomethingThatUsesTemperatureRepository(t *testing.T) {
//
//         // make and configure a mocked TemperatureRepository
//         mockedTemperatureRepository := &TemperatureRepositoryMock{
//             GetFunc: func() (Temperature, error) {
// 	               panic("mock out the Get method")
//             },
//         }
//
//         // use mockedTemperatureRepository in code that requires TemperatureRepository
//         // and then make assertions.
//
//     }
type TemperatureRepositoryMock struct {
	// GetFunc mocks the Get method.
	GetFunc func() (Temperature, error)

	// calls tracks calls to the methods.
	calls struct {
		// Get holds details about calls to the Get method.
		Get []struct {
		}
	}
}

// Get calls GetFunc.
func (mock *TemperatureRepositoryMock) Get() (Temperature, error) {
	if mock.GetFunc == nil {
		panic("TemperatureRepositoryMock.GetFunc: method is nil but TemperatureRepository.Get was just called")
	}
	callInfo := struct {
	}{}
	lockTemperatureRepositoryMockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	lockTemperatureRepositoryMockGet.Unlock()
	return mock.GetFunc()
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//     len(mockedTemperatureRepository.GetCalls())
func (mock *TemperatureRepositoryMock) GetCalls() []struct {
} {
	var calls []struct {
	}
	lockTemperatureRepositoryMockGet.RLock()
	calls = mock.calls.Get
	lockTemperatureRepositoryMockGet.RUnlock()
	return calls
}
